<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dell_New" failures="16" tests="62" name="Runner.CucumberRunner" time="32.475" errors="5" timestamp="2025-02-14T16:59:58 EST" skipped="0">
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.422">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.415"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.391"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.342"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.398"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.400">
    <error message="The step &#039;The API should return a status code 200 OK&#039; is undefined.
You can implement this step using the snippet(s) below:

@Then(&quot;The API should return a status code {int} OK&quot;)
public void the_api_should_return_a_status_code_ok(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'The API should return a status code 200 OK' is undefined.
You can implement this step using the snippet(s) below:

@Then("The API should return a status code {int} OK")
public void the_api_should_return_a_status_code_ok(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:136)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.440">
    <failure message="Status code doesn&#039;t match expected [201] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [201] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:98)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.389"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.411"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="3.242">
    <error message="The step &#039;The API should return a status code 200 and all the users with expected json response body&#039; is undefined.
You can implement this step using the snippet(s) below:

@Then(&quot;The API should return a status code {int} and all the users with expected json response body&quot;)
public void the_api_should_return_a_status_code_and_all_the_users_with_expected_json_response_body(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'The API should return a status code 200 and all the users with expected json response body' is undefined.
You can implement this step using the snippet(s) below:

@Then("The API should return a status code {int} and all the users with expected json response body")
public void the_api_should_return_a_status_code_and_all_the_users_with_expected_json_response_body(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:136)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.409">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.265"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.018">
    <error message="Invalid number of path parameters. Expected 1, was 0. Undefined path parameters are: userId." type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Invalid number of path parameters. Expected 1, was 0. Undefined path parameters are: userId.
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.RequestSpecificationImpl.assertCorrectNumberOfPathParams(RequestSpecificationImpl.groovy:1263)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1369)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1147)
at io.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1369)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.FilterContext$next.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1686)
at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1369)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1692)
at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1369)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:184)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1369)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:268)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
at stepdefinition.putUser.admin_sends_a_put_request_to_the_invalid_endpoint(putUser.java:120)
at ✽.Admin sends a PUT request to the invalid endpoint(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/CPut.feature:45)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.394"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.403"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.403"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.409"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="2.912"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.435"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.411"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.413"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.409">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.402"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.401"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.413"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.413"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.406"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.410"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.420">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.386"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.326"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.400">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.430">
    <failure message="Status code doesn&#039;t match expected [409] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [409] but found [500]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.putUser.the_api_should_return_corresponding_status_code(putUser.java:80)
at ✽.The API should return corresponding status code(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/CPut.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.400">
    <failure message="Status code doesn&#039;t match expected [201] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [201] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_the_status_code_created(postUser.java:190)
at ✽.The Api should return the status code 201 Created(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:48)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.408"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.408"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.406"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.401"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.441"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.415"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.391">
    <failure message="Status code doesn&#039;t match expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.deleteUser.the_api_should_return_a_status_code_and_the_user_record_should_be_deleted(deleteUser.java:39)
at ✽.The API should return a status code 200 and the user record should be deleted(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/Delete.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.430"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.403"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.359"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.389"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.418"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.407"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.272"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="3.184">
    <failure message="Status code doesn&#039;t match expected [404] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.getUser.the_api_should_return_a_status_code_not_found(getUser.java:84)
at ✽.The API should return a status code 404 Not Found(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/BGet.feature:22)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.432">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.407">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.455">
    <error message="The step &#039;The API should return a status code 200 OK&#039; is undefined.
You can implement this step using the snippet(s) below:

@Then(&quot;The API should return a status code {int} OK&quot;)
public void the_api_should_return_a_status_code_ok(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'The API should return a status code 200 OK' is undefined.
You can implement this step using the snippet(s) below:

@Then("The API should return a status code {int} OK")
public void the_api_should_return_a_status_code_ok(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:136)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.404">
    <failure message="Status code doesn&#039;t match expected [409] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [409] but found [400]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.putUser.the_api_should_return_corresponding_status_code(putUser.java:80)
at ✽.The API should return corresponding status code(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/CPut.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.420"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.251"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.419"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.419">
    <failure message="Status code doesn&#039;t match expected [400] but found [409]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [409]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.005">
    <error message="The step &#039;Admin create Get request with  invalid credential&#039; is undefined.
You can implement this step using the snippet(s) below:

@Given(&quot;Admin create Get request with  invalid credential&quot;)
public void admin_create_get_request_with_invalid_credential() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'Admin create Get request with  invalid credential' is undefined.
You can implement this step using the snippet(s) below:

@Given("Admin create Get request with  invalid credential")
public void admin_create_get_request_with_invalid_credential() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:136)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.929">
    <failure message="Status code doesn&#039;t match expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_corresponding_status_code_and_status_line(postUser.java:107)
at ✽.The API should return corresponding status code and status line(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.255"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.411"/>
  <system-out/>
  <testcase classname="Runner.CucumberRunner" name="runScenario" time="0.398">
    <failure message="Status code doesn&#039;t match expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code doesn't match expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at Utilities.Assertion.validateStatusCode(Assertion.java:27)
at stepdefinition.postUser.the_api_should_return_the_status_code_bad_request(postUser.java:201)
at ✽.The Api should return the status code 400 Bad Request(file:///C:/Users/karth/eclipse-workspace/UserAPI/src/test/resources/Features/APost.feature:53)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.CucumberRunner -->
